## Idiomatisk Python

Gezerlis mål med boken är inte bara att implementera färdigskrivna bibliotekers numeriska funktioner men att också försöka *förstå* varför en given numerisk metod fungerar. Därför utvecklas de flesta funktioner som används från grunden istället för att plockas direkt från hyllan $\texttt{färdiga funktioner}$.

Pythonkoder bör vara läsbara av människor så vi försöker att undvika för många genvägar och "smarta" tricks. Vi ska i ävrigt också själva kunna läsa koden när vi återkommer till den senare och har glömt vad vi höll på med.

Börja alltid med att designa koden i ord. Strukturera tankarna så det blir tydligt vad som ska åstadkommas. Detta leder till färre bugs i koden och därmed mindre tid till debugging. Och kör alltid tests av koden inklusive prints av avgörande variabler och liknande. Den måste fungera, inte bara se bra ut. 

#### Enkla funktioner
Strukturera koden runt *enkla* funktioner, inte funktioner som försöker att göra flera saker samtidigt. Kodens olika delar ska separeras tydligt och sen kombineras till en mera komplex helhet. Notera i övrigt att Pythonfunktioner kan användas som argument i andra funktioner vilket är lämpligt när vi ofta vill skicka en funktion in som parameter i någon annan funktion men vi samtidigt vill ha möjlighet att lätt ändra parametern utan att manuellt ändra argumenten inuti funktionen som tar en annan funktion som argument. 

Vidare kan funktioner lätt användas på varje element i en lista om vi utnyttjar *list comprehension* så till exempel för någon funktion $\texttt{f}$ som har definierats på egen hand och vars uttryck returneras när vi ropar på den kan vi skrivas

\begin{align*}
\texttt{newlist = [f(x) for x in xlist]}
\end{align*}

för någon lista $\texttt{xlist}$ där nya listan således blir en lista med alla funktionsvärden för variablarna från $\texttt{xlist}$.

I allmänhet rekommenderas det att inte låta funktioner ändra till exempler lister eller annat som ligger utanför funktionen. Istället returneras ett svar från funktionen som sen kan användas utanför funktionsmiljön.

#### Iterera över listelement, inte listindex
Man kan vara benägen att använda index $\texttt{i}$ i en $\texttt{for}$ loop och sen loopa genom $\texttt{len(xlist)}$ som

\begin{align*}
\texttt{for i in range(len(xlist)):}
\end{align*}

men en styrka i Python är att man helt enkelt kan iterera över elementen själva som

\begin{align*}
\texttt{for x in xlist:}
\end{align*}

och vill man sen också kunna använda indexet någonstans i loopen kan man använda 

\begin{align*}
\texttt{for i, x in enumerate(xlist):}
\end{align*}

som därmed både tillåter användning av indexet $\texttt{i}$ *och* variabeln $\texttt{x}$ från listan. Enumerate uppräknar med andra ord alla variablarna medan den loopar genom den.

Har vi *två listor* tänker vi likadant som med en lista i Python. Vi zipper ned dem i en gemensam datastruktur med inbyggda $\texttt{zip()}$ funktionen som bildar en itererbar enhet som innehåller tupler, de två ingående listorna blir därför nu oföränderliga strukturer inuti zippade strukturen (vilket är bra, eftersom vi inte vill ändra dem just nu, vi vill använda deras innehåll). Loops över två listor kan uttryckas

\begin{align*}
\texttt{for x, y in zip(xlist, ylist)}
\end{align*}

Nu kommer vi i varje iteration av loopen att ta både nästa x och nästa y och använda där variablerna ingår i koden.

Vi kan även använda en funktion i en lista och i listan kombinera två lister som har zippats ihop så vi till exempel låter ena listans variabler opererera på funktionsvärden av andra listans variabler som i exemplet nedan.

\begin{align*}
\texttt{z = [y*f(x) for x, y in zip(xlist, ylist):]}
\end{align*}

#### For-else loops
Ett exempel på en mycket användbar loop är $\texttt{for-else}$ loopen som exemplifieras nedan. En $\texttt{for-else}$ gör bland annat att vi kan söka efter något element inuti en följd av element och vi till exempel bara vill utföra någon operation på de element i följden som vi hittar. 

Vi har en lista med namn och vi vill undersöka om ett givet namn finns med på listan. Finns det med skriver vi ut det och fortsätter genom listan, annars fortsätter vi bara genom listan.

Notera hur loopen placeras i en funktion och hur $\texttt{else}$ är på samma kodnivå som $\texttt{for}$, inte på samma nivå som $\texttt{if}$ vilket vi kanske är mera vana vid. I det här fallet fungerar $\texttt{else}$ som det funktionen returnerar om inte $\texttt{for}$ loopen har hittat et namn i listan. 

In [1]:
names = ['Alice', 'Bob', 'Chris', 'Denise']

def check_name(check, names):
    for name in names:
        if name == check:
            return f'{name} is already on the list'
    else:
        names.append(check)
        return f'{check} has been added to the list'

print('The people on the original list were:')
for name in names:
    print(name, end=", ")

print(f'\n')
    
new_names = ['Alice', 'Peter', 'Chris', 'Mary']
for person in new_names: 
    print(check_name(person, names))
    
print('\nThe names on the updated list are:')
for name in names:
    print(name, end=", ")

The people on the original list were:
Alice, Bob, Chris, Denise, 

Alice is already on the list
Peter has been added to the list
Chris is already on the list
Mary has been added to the list

The names on the updated list are:
Alice, Bob, Chris, Denise, Peter, Mary, 

#### Endimensionella NumPy arrays

$\texttt{NumPy}$ är ett bibliotek av funktioner i Python som har byggts specifikt för att hantera *Numerisk Python*. Den centrala datastrukturen i NumPy är *arrayer*, listor som bara kan bestå av en typ av element, till exempel heltal eller strings eller annat. 

En av styrkorna med en sådan array är att vi kan utföra en given operation på alla elementen i array samtidigt. Vi behöver med andra ord inte skriva det som en list comprehension. Endimensionella arrays är således att jämföra med listor och ersätter helt enkelt listor som datastruktur i NumPy.

Till exempel om $\texttt{xs}$ är en array då är $\texttt{ys = 5*xs}$ arrayen där alla element är 5 gånger respektive element i $\texttt{xs}$. Och likadant kan funktioner som $\texttt{np.sqrt()}$ hantera kvadratroten ur alla elementen jämfört med funktioner från till exempel $\texttt{math}$ biblioteket som hanterar operationer elementvist. 

Notera hur arrayen nedan bildas från en lista av element. Testa att bilda en array från en lista med element av olika elementtyper och se att det genererar ett felmeddelande. 

In [2]:
import numpy as np

xs = np.array([1, 2, 3, 4])
ys = 5*xs
print(xs)
print(ys)

[1 2 3 4]
[ 5 10 15 20]


Notera att i motsättning till för listor så påverkas en ursprunlig array om vi till exempel tar en slice av den och gör den till en ny array för att slutligen ändra ett av elementen i nya arrayen. Ursprunliga arrayen ändras då också.

In [3]:
ys = xs[:3]
print(ys)

ys[1] = 100
print(xs)

[1 2 3]
[  1 100   3   4]


Vi använder därför till exempel $\texttt{np.copy()}$ för att kopiera en hel lista eller $\texttt{np.copy(xs[a:b])}$ för att *kopiera* en slice av en annan array.

En annan styrka är att $\texttt{xs + ys}$ ger en ny array där varje element är summan av respektive element i ursprungsarrayen. Förutsat  alltså att det finns samma antal av samma typ element i varje array. (Summor av listor sammanlänkar [*concatenate*] elementen). 

In [56]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])

a3 = a2 + a1
print(a3)

[5 5 5 5]


**np.where()**

Funktionen $\texttt{np.where()}$ hjälper oss att hitta vilka *index* som motsvarar ett givet värde.

In [5]:
print(np.where(a1 == 2))

(array([1]),)


#### Två- och tredimensionella NumPy arrays - matriser och matriser av arrays
Matriser kan bildas manuellt som lister av lister. En matris är därmed en tvådimensionell array till exempel på formen

In [6]:
matris1 = np.array([[1, 2, 3], [4, 5, 6]])
print(matris1)

[[1 2 3]
 [4 5 6]]


Notera alltså hur vi får en matris och inte en lista av listor när vi stoppar listan av listor in i en arrayfunktion.

Men vi kan också bilda matriser med de arrayfunktioner som vi bildar vektorer (listliknande) arrays med. I exemplet nedan anger vi rader och kolumner som $(m,n)$ i första matrisen och i den andra utnyttjar vi $\texttt{identity}$ till att bilda en identitetsmatris med den angivna dimensionen.

In [7]:
matris2 = np.ones((6, 3))
print(matris2)

matris3 = np.identity(5)
print(matris3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Observera att begreppet "dimension" i Python skiljer sig från linjära algebrans dimensionsbegrepp som beskrivs av $m\times n$ strukturen av en given matris. För en matris i Python gäller rumsliga dimensioner. Således är vektorer endimensionella, matriser är tvådimensionella och matriser av matriser (arrays) är tredimensionella. 

Dimensionerna för två olika matriser visas nedan. I fallet $\texttt{matris4}$ bildas själva matrisen av arrayfunktionen $\texttt{np.arange()}$ tillsammans med $\texttt{.reshape}$ funktionen som omvandlar en given endimensionell array över något intervall till två matriser inuti en samlad matris. 

Det är dock nödvändigt att antalet element vi vill placera i matrisen motsvarar produkten av värden i $\texttt{.reshape}$. I det aktuella exemplet bildar vi en samlad matris av tre $2\times 2$ matriser från elementen som ges i $\texttt{np.arange()}$.

In [8]:
print(np.ndim(matris2))

2


In [35]:
matris4 = np.arange(3, 15).reshape(3, 2, 2)
print(matris4)
print(f'\nDimensionen av matris4 är {np.ndim(matris4)}')

[[[ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]

Dimensionen av matris4 är 3


För att tillgå ett element i en matris använder vi oss av samma $A_{ij}$ indexeringsmetod som vi är vana vid. Således kan vi skriva ut ett element som nedan. Notera att det fortfarande är Pythons indexeringsformat som används så element $[2, 1]$ är till exempel *tredje* raden *andra* kolumnen:

In [34]:
print(matris4[2, 1])

[13 14]


Vi kan göra slices av matriser som nedan för matrisen A där vi väljer ut en given rad och sen alla elementen i den raden.

In [37]:
A = np.arange(1, 5).reshape(2, 2)
print(A)
print(A[1,:])

[[1 2]
 [3 4]]
[3 4]


I en lite större matris kan vi skära ut en block av element eller en rad mitt i matrisen eller vad vi nu vill. Ett par exempel ges nedan. 

Först skär vi ut ett $2\times3$ block och sen skär vi utt mitterkolumnen. Slutligen skär vi ut ett block utan första och andra kolumnen.

Notera återigen Pythonkonventionen kring indexering. Vi *börjar* med värdet $a$ men vi tar inte med $b$ i notationen $\texttt{[a:b]}$. Vidare kan vi utnyttja att $-1$ alltid tar med sista kolumnen / elementet i ett intervall.

In [50]:
B = np.arange(1,13).reshape(3, 4)

print(B)

print(B[1:2, :])

print(B[1:2, :])

print(B[0:3, 1:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6 7 8]]
[[5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]


**Matrismultiplikation** tar olika former.

Specifikt ger produkten av två arrays den så kallade *Hadamard* produkt som är elementvis multiplikation i motsättning till linjära algebrans multiplikation.

Matrismultiplikation utnyttjar istället $@$ eller $\texttt{np.dot()}$ funktionen som nedan. Notera hur $\texttt{np.dot()}$ automatiskt blir skalärprodukten av två vektorer när två endimensionella arrays multipliceras med varandra. Vi behöver således inte transponera ena vektorn för att ta skalärprodukten av vektorerna. Men *om* vi vill åstadkomma en $n\times n$ matris från produkten av två $n\times 1$ matriser då kan vi göra detta genom att ta $\href{https://en.wikipedia.org/wiki/Outer_product}{\textbf{yttre } produkten}$ $A\bigotimes B$ av matriserna. Beroende av ordningen på ingående matriserna bildas *två olika* $n\times n$ matriser (!)

**Division** av alla matriselement kan utnyttjas som nedan. Vi kan således både dividera alla element i matrisen med samma nämnare och vi kan dividera ledvist mellan två matriser.

In [71]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(2, 6).reshape(2, 2)

C = np.dot(A, B)
print(C)
D = A@B
print(D)

# a1 och a2 som ovan
a4 = np.dot(a1, a2)
print(a4)

print(D/(2*np.pi))
print(B/A)

# bilda en n x n matris
E = np.arange(1,5)
F = np.arange(2,6)

# två olika n x n matriser
print(np.outer(F,E))
print(np.outer(E,F))

[[10 13]
 [22 29]]
[[10 13]
 [22 29]]
20
[[1.59154943 2.06901426]
 [3.50140875 4.61549335]]
[[2.         1.5       ]
 [1.33333333 1.25      ]]
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
[[ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]]
